name: RFC propose

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  rfc-propose:
    name: Propose an RFC creation transaction
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rfc') }}
    runs-on: ubuntu-latest
    steps:
      - uses: paritytech/rfc-action@rzadp/fellowship-process-bot
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
